# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuyingAgent' do

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTImage',
]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'AppAuth', '>= 0.94'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'


end
